config/routes.rb
EstagiandoUFF::Application.routes.draw do

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  get 'autocomplete_empresas' => 'avaliacoes#autocomplete_empresas'

  root :to => "usuarios#home"

  resources :usuarios do
    collection do
      get 'cadastro_efetuado'
    end
    member do
      get :confirm_email
      post :admin
    end
  end

  resources :comentarios

  resources :avaliacoes  do
    collection do
      get 'pesquisar'
    end
    member do
      post :aceitar
      post :rejeitar
    end
  end

  resources :SituacaoAvaliacoesController

  resources :empresas

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  attr_accessible :data, :id, :texto, :usuario_id, :avaliacao_id

  belongs_to :avaliacao
  belongs_to :usuario
end

app/controllers/comentarios_controller.rb
# encoding : utf-8
class ComentariosController < ApplicationController
  load_and_authorize_resource :except => [:index, :show]

  def index
    @comentarios = Comentario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  def create
    @comentario = Comentario.new(params[:comentario])
    @comentario.usuario_id = current_user.id

      if @comentario.save
        redirect_to avaliacao_path(@comentario.avaliacao_id), :flash => { :notice => 'Comentário postado com sucesso!.' }
      else
        redirect_to :back, :flash => { :error => 'Erro ao postar comentário.' }
      end

  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @avaliacao_id = @comentario.avaliacao_id
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to avaliacao_path(@avaliacao_id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<% if comentario.usuario == current_user %>
    <li class="by-me">

      <div class="avatar pull-left">
        <a href="<%= usuario_path(comentario.usuario_id) %>">
          <%= image_tag("user.jpg", width: "30", height: "30", :class => 'img-circle img-responsive') %>
        </a>
      </div>

      <div class="chat-content">
        <div class="chat-meta"><a href="<%= usuario_path(comentario.usuario_id) %>"><%= comentario.usuario.nome %></a><span class="pull-right"><%= comentario.created_at.strftime("%d/%m/%Y às %H:%M") %></span></div>
        <%= comentario.texto %>

        <%if can? :modify, comentario %>
            <br>
            <div class="btn-group btn-group-xs" role="group" style="float: right; margin-top: 5px;">
              <%= link_to "", comentario_path(comentario), :method => :delete, :class => "btn btn-danger fa fa-trash-o", :data => {:confirm => ("Tem certeza que deseja excluir esse comentário?")}%>
            </div>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </li>

<% else %>

    <li class="by-other">

      <div class="avatar pull-right">
        <a href="<%= usuario_path(comentario.usuario_id) %>">
          <%= image_tag("user.jpg", width: "30", height: "30", :class => 'img-circle img-responsive') %>
        </a>
      </div>

      <div class="chat-content">
        <div class="chat-meta"><%= comentario.created_at.strftime("%d/%m/%Y às %H:%M") %><span class="pull-right"><a href="<%= usuario_path(comentario.usuario_id) %>"><%= comentario.usuario.nome %></a></span></div>
        <%= comentario.texto %>

        <%if can? :modify, comentario %>
            <br>
            <div class="btn-group btn-group-xs" role="group" style="float: right; margin-top: 5px;">
              <%= link_to "", comentario_path(comentario), :method => :delete, :class => "btn btn-danger fa fa-trash-o", :data => {:confirm => ("Tem certeza que deseja excluir esse comentário?")}%>
            </div>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </li>
<% end %>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
    <% if @comentario.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

          <ul>
            <% @comentario.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :avaliacao_id, :value => avaliacao.id %>

    <%= f.text_area :texto, :rows => 6, :style => 'width: 100%; padding: 10px'  %>

    <br><br>

    <div class="actions" style="text-align: center;">
      <%= f.submit "Enviar Comentário", :class => 'btn btn-success'%>
    </div>


<% end %>

app/views/comentarios/edit.html.erb
<% content_for :content do %>

    <%= render 'form' %>

<% end %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Texto</th>
    <th>Data</th>
    <th>Usuario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.id %></td>
    <td><%= comentario.texto %></td>
    <td><%= comentario.data %></td>
    <td><%= comentario.usuario_id %></td>
    <td><%= link_to 'Show', comentario %></td>
    <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<% content_for :content do %>

    <%= render 'form' %>

<% end %>

app/views/comentarios/show.html.erb
<% content_for :content do %>

    <div class="row">
      <div class="col-lg-1"></div>
      <div class="col-lg-10">
        <section class="panel">
          <div class="panel-body">

            <%= render :partial => "comentarios/comentario", :locals => {:comentario => @comentario} %>

          </div>
        </section>
      </div>
    </div>


<% end %>