config/routes.rb
EstagiandoUFF::Application.routes.draw do

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  get 'autocomplete_empresas' => 'avaliacoes#autocomplete_empresas'

  root :to => "usuarios#home"

  resources :usuarios do
    collection do
      get 'cadastro_efetuado'
    end
    member do
      get :confirm_email
      post :admin
    end
  end

  resources :comentarios

  resources :avaliacoes  do
    collection do
      get 'pesquisar'
    end
    member do
      post :aceitar
      post :rejeitar
    end
  end

  resources :SituacaoAvaliacoesController

  resources :empresas

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :administrador, :email, :id, :nome, :senha, :email_confirmed, :confirm_token
  validates :senha, length: { minimum: 6 }

  has_many :comentarios
  has_many :avaliacoes

  before_create :confirmation_token

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private
  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

app/controllers/usuarios_controller.rb
# encoding : utf-8
class UsuariosController < ApplicationController

  def home
    if logged_in?
      redirect_to current_user
    else
      @usuario = Usuario.new
    end
  end

  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  def admin
    @usuario = Usuario.find(params[:id])
    @usuario.administrador = !@usuario.administrador
    if @usuario.save
      redirect_to usuarios_path, notice: "Tipo de conta do usuário #{@usuario.nome} salvo com sucesso."
    else
      redirect_to usuarios_path, :flash[:error] = "Erro ao alterar o tipo de conta do usuário #{@usuario.nome}: #{@usuario.errors}"
    end
  end

  def show
    @usuario = Usuario.find(params[:id])
    if logged_in? && current_user.id == @usuario.id
      @avaliacoes = Avaliacao.where(:usuario_id => @usuario.id)
    else
      @avaliacoes = Avaliacao.moderadas.do_usuario_id(@usuario.id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def cadastro_efetuado

  end

  def create
    if params[:usuario][:email].include? "@"
      if !(params[:usuario][:email].include? "id.uff.br")
        flash[:error] = "Email incorreto. Para se cadastrar no sistema, você precisa informar um email @id.uff.br."
        redirect_to root_url and return
      end
    else
      email = params[:usuario][:email]+ "@id.uff.br"
    end
    if Usuario.where(:email => email).any?
      flash[:error] = "Já existe um cadastro com esse email."
      redirect_to root_url and return
    else
      @usuario = Usuario.new(params[:usuario])
      @usuario.email = email
      @usuario.administrador = 0

      respond_to do |format|
        if @usuario.save
          UserMailer.registration_confirmation(@usuario).deliver
          format.html { redirect_to cadastro_efetuado_usuarios_path, notice: @usuario.email }
        end
      end
    end
  end

  def update
    @usuario = Usuario.find(params[:id])
    if @usuario.update_attributes(params[:usuario])
      redirect_to @usuario, notice: 'Dados editados com sucesso.'
    else
      redirect_to edit_usuario_path(@usuario), :flash => {:error => "Os dados não puderam ser atualizados. Erro(s): #{@usuario.errors.messages}"}
    end
  end

  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuário apagado." }
      format.json { head :no_content }
    end
  end

  def confirm_email
    @usuario = Usuario.find_by_confirm_token(params[:id])
    if @usuario
      @usuario.email_activate
      redirect_to root_path, notice: "Bem vindo(a) ao EstagiandoUFF! Sua conta foi verificada. Por favor, faça login para prosseguir."
    else
      flash[:error] = "Usuário não existente."
      redirect_to root_url
    end
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario, :html => {:class => "form-horizontal"})  do |f| %>

    <div class="row">
      <div class="col-xs-12 col-lg-2"></div>
      <div class="col-xs-12 col-lg-8">
        <section class="panel">
          <div class="panel-body">

            <div class="form-group">
              <label for="cadastroNome" class="col-lg-2 control-label">Nome</label>
              <div class="col-lg-10">
                <%= f.text_field :nome, :class => 'form-control', :placeholder => 'Nome' %>
              </div>
            </div>
            <div class="form-group">
              <label for="cadastroEmail" class="col-lg-2 control-label">Email</label>
              <div class="col-lg-10">

                <div class="input-group">
                  <%= f.text_field:email,:class => 'form-control', :placeholder => 'Email', :value => @usuario.email.split("@")[0] %>
                  <span class="input-group-addon" id="basic-addon2">@id.uff.br</span>
                </div>

              </div>
            </div>
            <div class="form-group">
              <label for="cadastroSenha" class="col-lg-2 control-label">Senha</label>
              <div class="col-lg-10">
                <%= f.password_field :senha, :class => 'form-control', :placeholder => 'Senha', value: @usuario.senha %>
              </div>
            </div>
            <div class="form-group">
              <div style="text-align: center">
                <%= f.submit "Salvar", :class => 'btn btn-success'%>
              </div>
            </div>

          </div>
        </section>
      </div>
    </div>

<% end %>

app/views/usuarios/cadastro_efetuado.html.erb
<% content_for :content do %>

        <div class="row" style="position:absolute; top: 50%; margin:-100px 0 0 0;">
          <div class="col-lg-2"></div>

          <div class="col-xs-12 col-lg-8">
            <section class="panel">
              <div class="panel-body">

                <h1 style="text-align: center">Seu cadastro está quase finalizado...</h1>

                <p>Nós enviamos um email para <b><%= notice %></b> com um link para você realizar a ativação do seu cadastro.
                Essa medida é importante pois o EstagiandoUFF é um sistema fechado para alunos da Universidade Federal Fluminense,
                portanto precisamos verificar se o seu email <b>@id.uff.br</b> é válido.</p>
                <p style="text-align: center">Você será redirecionado para página inicial em alguns segundos...
                <br><span style="font-size: 8.5pt; color: #989595;">Se não quiser esperar, <a href="<%= root_path %>">clique aqui.</a></span></p>

                <script type="text/javascript">
                  $(document).ready(function() {
                    setTimeout(function () {
                        window.location.href = "<%= root_path %>"; //will redirect to your blog page (an ex: blog.html)
                    }, 2000);
                  })
                </script>

              </div>
            </section>
          </div>
        </div>

<% end %>

app/views/usuarios/edit.html.erb
<% content_for :content do %>

    <ol class="breadcrumb">
      <li><i class="fa fa-home"></i><a href="<%= root_path %>">Início</a></li>
      <li><i class="fa fa-user"></i><a href="<%= usuarios_path %>">Usuários</a></li>
      <li><i class="fa fa-pencil-square-o"></i><a href="<%= usuario_path %>"><%= @usuario.nome %></a></li>
    </ol>

    <%= render 'form' %>

<% end %>

app/views/usuarios/home.html.erb
<% content_for :content do %>

        <!--overview start-->

        <div class="row">
          <div class="col-xs-12 col-lg-8">
            <section class="panel">
              <div class="panel-body">

                <h1 style="text-align: center; font-size: 22pt;">Seja bem-vindo ao <b>EstagiandoUFF</b>!</h1>

                <p>O <b>EstagiandoUFF</b> é uma rede social exclusivamente para os alunos da <i>Universidade Federal Fluminense</i>.
                Aqui os usuários podem compartilhar as suas experiências em estágios e interagir com outros usuários sobre
                as suas experiências.</p>
                <p>Como nosso sistema é exclusivo para alunos da UFF, é necessário efetuar o seu registro utilizando um email
                <b>@id.uff.br</b>. Porém, nosso sistema é completamente aberto para visualização externa.
                Isto é, visitantes não cadastrados podem visualizar as avaliações e os comentários feitos pelos usuários
                cadastrados no sistema.</p>
                <p>No menu ao lateral, você encontra as opções Home, Empresas e Avaliações.</p>
                <ul>

                  <li style="margin-bottom: 10px;"><b>Home</b> - redireciona à página inicial (esta página)</li>
                  <li style="margin-bottom: 10px;"><b>Empresas</b> - lista das empresas já adicionadas ao nosso sistema. Nesta página é possível filtrar as empresas
                  exibidas, bem como buscar uma empresa pelo seu nome.</li>
                  <li style="margin-bottom: 10px;"><b>Avaliações</b> - lista das avaliações de estágio realizadas pelos nossos usuários. Aqui é possível filtrar
                  os resultados de diversas maneiras.</li>

                </ul>

              </div>
            </section>
          </div>

          <% if !logged_in? %>
          <div class="col-xs-6 col-lg-4">

            <ul class="nav nav-tabs">
              <li class="active">
                <a data-toggle="tab" href="#login"><i class="fa fa-user"></i> Login</a>
              </li>
              <li><a data-toggle="tab" href="#cadastro"><i class="fa fa-plus"></i> Cadastro</a></li>
            </ul>
            <div class="tab-content panel">
              <div id="login" class="tab-pane panel-body fade in active">

                <p style="margin-top: 5px;">Faça login utilizando seu email <b>@id.uff.br</b>.</p>
                <p style="margin-bottom: 20px;">Se essa for a sua primeira visita ao <b>EstagiandoUFF</b>, será necessário realizar um <a href="<% new_usuario_path %>">cadastro</a>.</p>



                <%= form_for :session, :url=> sign_in_path, :html => {:class => "form-horizontal"} do |ff| %>
                  <div class="form-group">
                    <label for="loginEmail" class="col-lg-2 control-label">Email</label>
                    <div class="col-lg-10">

                      <div class="input-group">
                        <%= ff.text_field :email, autofocus: true, :class=> "form-control", :placeholder=>"Email" %>
                        <span class="input-group-addon" id="basic-addon2">@id.uff.br</span>
                      </div>

                    </div>
                  </div>
                  <div class="form-group">
                    <label for="loginSenha" class="col-lg-2 control-label">Senha</label>
                    <div class="col-lg-10">
                      <%= ff.password_field :senha, autocomplete: "off", :class=> "form-control", :placeholder=>"Senha" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div style="text-align: center">
                      <%= ff.submit "Entrar", :class => 'btn btn-success'%>
                    </div>
                  </div>
              <% end %>

              </div>

              <div id="cadastro" class="tab-pane panel-body fade">
                <p style="margin-top: 5px;">Faça já o seu cadastro no <b>EstagiandoUFF</b>.</p>
                <p style="margin-bottom: 20px;">Por ser um sistema exclusivo para alunos da UFF, você deve efetuar seu cadastro usando seu email <b>@id.uff.br</b></p>

                <%= form_for(@usuario, :html => {:class => "form-horizontal"}) do |f|%>
                  <div class="form-group">
                    <label for="cadastroNome" class="col-lg-2 control-label">Nome</label>
                    <div class="col-lg-10">
                      <%= f.text_field :nome, :class => 'form-control', :placeholder => 'Nome' %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="cadastroEmail" class="col-lg-2 control-label">Email</label>
                    <div class="col-lg-10">

                      <div class="input-group">
                        <%= f.text_field :email, :class => 'form-control', :placeholder => 'Email' %>
                        <span class="input-group-addon" id="basic-addon2">@id.uff.br</span>
                      </div>

                    </div>
                  </div>
                  <div class="form-group">
                    <label for="cadastroSenha" class="col-lg-2 control-label">Senha</label>
                    <div class="col-lg-10">
                      <%= f.password_field :senha, :class => 'form-control', :placeholder => 'Senha' %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div style="text-align: center">
                      <%= f.submit "Cadastrar", :class => 'btn btn-success'%>
                    </div>
                  </div>
                <% end -%>
              </div>
            </div>
          </div>
          <% end %>
        </div>


        <!-- project team & activity end -->
<% end
%>

app/views/usuarios/index.html.erb
<% content_for :content do %>

    <h1><i class="fa fa-user"></i> Lista de Usuários</h1>

    <ol class="breadcrumb" style="margin-top: 30px;">
      <li><i class="fa fa-home"></i><a href="<%= root_path %>">Início</a></li>
      <li><i class="fa fa-user"></i><a href="<%= usuarios_path %>">Usuários</a></li>
      <li><i class="fa fa-plus"></i>Lista de Usuários</li>
    </ol>

    <div class="row">
      <div class="col-lg-12">
        <section class="panel">

          <table class="table table-striped table-advance table-hover">
            <tbody>
            <tr>
              <th><i class="fa fa-user"></i> Nome</th>
              <th><i class="fa fa-flah"></i> Email</th>
              <th><i class="fa fa-flah"></i> Tipo</th>
              <th><i class="fa fa-cogs"></i> Ações</th>
            </tr>
            <% @usuarios.each do |usuario| %>
                <tr>
                  <td><a href="<%= usuario_path(usuario.id) %>"><%= usuario.nome %></a></td>
                  <td><%= usuario.email %></td>
                  <td><%= usuario.administrador ? "Administrador" : "Aluno" %></td>
                  <td>
                    <div class="btn-group">
                      <%= link_to "", usuario_path(usuario), :class => "btn btn-primary fa fa-plus-square-o", :title => "Detalhar"%>
                      <%= link_to "", usuario_path(usuario), :method => :delete, :class => "btn btn-danger fa fa-trash-o", :data => {:confirm => ("Tem certeza que deseja excluir essa usuario?")}, :title => "Excluir"%>
                      <% if !usuario.administrador %>
                          <%= link_to "", admin_usuario_path(usuario), :method => :post, :class => "btn btn-success fa fa-check-square-o", :data => {:confirm => ("Tem certeza que deseja tornar esse usuário administrador?")}, :title => "Tornar Administrador"%>
                      <%else%>
                          <%= link_to "", admin_usuario_path(usuario), :method => :post, :class => "btn btn-warning fa fa-times", :data => {:confirm => ("Tem certeza que deseja retirar os privilégios de administrador desse usuário?")}, :title => "Tirar Privilégios de Administrador"%>
                      <%end%>
                    </div>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </section>
      </div>
    </div>

<% end %>

app/views/usuarios/new.html.erb
<% content_for :content do %>

    <h1><i class="fa fa-user"></i> Novo Usuário</h1>

    <ol class="breadcrumb" style="margin-top: 30px;">
      <li><i class="fa fa-home"></i><a href="<%= root_path %>">Início</a></li>
      <li><i class="fa fa-user"></i><a href="<%= usuarios_path %>">Usuários</a></li>
      <li><i class="fa fa-plus"></i>Novo Usuário</li>
    </ol>

    <%= render 'form' %>

<% end %>

app/views/usuarios/show.html.erb
<% content_for :content do %>

    <ol class="breadcrumb">
      <li><i class="fa fa-home"></i><a href="<%= root_path %>">Início</a></li>
      <li><i class="fa fa-user"></i><a href="<%= usuarios_path %>">Usuários</a></li>
      <li><%= @usuario.nome %></li>
    </ol>

    <div class="row">

      <div class="col-xs-12 col-lg-1"></div>

      <div class="col-xs-12 col-lg-2">
        <section style="margin-bottom: 15px;">
          <%= image_tag("user.jpg", :class => 'img-circle img-responsive') %>
        </section>
      </div>

      <div class="col-xs-12 col-lg-8">
        <section class="panel">
          <div class="panel-body">

            <% if @usuario == current_user %>
                <a class="btn btn-primary" href="<%= edit_usuario_path(@usuario) %>" style="float:right;"><i class="fa fa-pencil-square-o"></i> Editar Perfil</a>
            <% end %>
            <p>
              <b>Nome:</b>
              <%= @usuario.nome %>
            </p>

            <p>
              <b>Email:</b>
              <%= @usuario.email %>
            </p>

          </div>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-lg-1"></div>
      <div class="col-xs-12 col-lg-10">
        <section class="panel">
          <div class="panel-body">

            <h2>Avaliações</h2>

            <% if !@avaliacoes.any? %>
                <div class="alert alert-warning fade in" style="margin-bottom: 0px !important;">

                  O usuário ainda não realizou nenhuma avaliação.

                </div>
            <% else %>
                <% @avaliacoes.each do |avaliacao| %>

                    <hr>
                    <div class="row">

                      <div class="col-xs-12 col-lg-3">
                        <p style="font-size: 12pt;">
                          <b>Empresa:</b>
                          <a href="<%= empresa_path(avaliacao.empresa.id) %>" target="_blank"><%= avaliacao.empresa.nome %></a>
                        </p>
                      </div>

                      <div class="col-xs-12 col-lg-3">
                        <p style="font-size: 12pt;">
                          <b>Período na empresa:</b>
                          <% if !avaliacao.inicio_contrato.nil? %>

                              <% if !avaliacao.final_contrato.nil? %>
                                  <%= avaliacao.inicio_contrato %> a <%= avaliacao.final_contrato %>
                              <% else %>
                                  <%= avaliacao.inicio_contrato %> até agora

                              <% end %>
                          <% else %>
                              <i>não informado</i>
                          <% end %>
                        </p>
                      </div>

                      <div class="col-xs-12 col-lg-3">
                        <p style="font-size: 12pt;">
                          <b>Cargo:</b>
                          <% if !avaliacao.titulo_cargo.nil? %>
                              <%= avaliacao.titulo_cargo %>
                          <% else %>
                              <i>não informado</i>
                          <% end %>
                        </p>
                      </div>

                      <% if logged_in? && current_user.id == @usuario.id%>
                          <div class="col-xs-12 col-lg-2">
                            <p style="font-size: 12pt;">
                              <b>Status:</b>
                              <%= avaliacao.situacao_avaliacao.descricao%>
                            </p>
                          </div>
                      <% end %>

                      <div class="col-xs-12 col-lg-1">
                        <a class="btn btn-primary" style="float: right" href="<%= avaliacao_path(avaliacao.id) %>"><i class="fa fa-plus-square-o"></i></a>
                      </div>
                    </div>
                <% end %>
            <% end %>

          </div>
        </section>
      </div>
    </div>

<% end %>