config/routes.rb
EstagiandoUFF::Application.routes.draw do

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  get 'autocomplete_empresas' => 'avaliacoes#autocomplete_empresas'

  root :to => "usuarios#home"

  resources :usuarios do
    collection do
      get 'cadastro_efetuado'
    end
    member do
      get :confirm_email
      post :admin
    end
  end

  resources :comentarios

  resources :avaliacoes  do
    collection do
      get 'pesquisar'
    end
    member do
      post :aceitar
      post :rejeitar
    end
  end

  resources :SituacaoAvaliacoesController

  resources :empresas

end

app/controllers/avaliacoes_controller.rb
# encoding : utf-8
class AvaliacoesController < ApplicationController
  load_and_authorize_resource :except => [:index, :show,:pesquisar]

  def index
    @avaliacoes = (logged_in? && current_user.administrador) ? Avaliacao.all : Avaliacao.moderadas
  end

  def show
    @avaliacao = Avaliacao.find(params[:id])
    @comentario = Comentario.new
  end

  def new
    @avaliacao = Avaliacao.new
  end

  def edit
    @avaliacao = Avaliacao.find(params[:id])
  end

  def create
    avaliacao = Avaliacao.where(:empresa_id=>params[:avaliacao][:empresa_id], :usuario_id => current_user.id)
    if avaliacao.any?
      redirect_to avaliacao.first, :flash => { :error => "Você já avaliou essa empresa." }
    else
      @avaliacao = Avaliacao.new(params[:avaliacao])
      @avaliacao.usuario_id = current_user.id
      @avaliacao.situacao_avaliacao_id = SituacaoAvaliacao::AGUARDANDO_MODERACAO

      if @avaliacao.save
        redirect_to @avaliacao, :notice => 'Avaliação cadastrada com sucesso!'
      else
        render new_avaliacao_path, :flash => { :error => "A avaliação não pode ser salva. Erros: #{@avaliacao.errors}." }
      end
    end
  end

  def update
    @avaliacao = Avaliacao.find(params[:id])
    @avaliacao.usuario_id = current_user.id

    if @avaliacao.update_attributes(params[:avaliacao])
      redirect_to @avaliacao, :notice => 'Avaliação atualizada com sucesso!.'
    else
      render edit_avaliacao_path, :flash => { :error => "A avaliação não pode ser alterada. Erros: #{@avaliacao.errors}." }
    end
  end

  def destroy
    @avaliacao = Avaliacao.find(params[:id])
    @avaliacao.destroy

    redirect_to root_path, :notice => 'Avaliação apagada com sucesso!.'
  end

  def aceitar
    @avaliacao = Avaliacao.find(params[:id])
    @avaliacao.situacao_avaliacao_id = SituacaoAvaliacao::ACEITA
    if @avaliacao.save
      redirect_to avaliacoes_path, :notice => 'Avaliação aceita!'
    else
      redirect_to @avaliacao, :flash => { :error => "Erro ao fazer a moderação da avaliação. Erro: #{@avaliacao.errors}."}
    end
  end

  def rejeitar
    @avaliacao = Avaliacao.find(params[:id])
    @avaliacao.situacao_avaliacao_id = SituacaoAvaliacao::REJEITADA
    if @avaliacao.save
      redirect_to avaliacoes_path, :notice => 'Avaliação rejeitada.'
    else
      redirect_to @avaliacao, :flash => { :error => "Erro ao fazer a moderação da avaliação. Erro: #{@avaliacao.errors}."}
    end
  end

  def autocomplete_empresas
    lista = []
    if params[:q].size >= 3
      empresas = Empresa.empresas_tokeninput(params[:q])
      empresas.each do |empresa|
        nome = empresa.nome
        lista.push :id => empresa.id,
                   :name => nome,
                   :img_src => nil
      end
    end
    respond_to do |format|
      format.json { render :json => lista }
    end
  end

  def pesquisar
    @avaliacoes = (logged_in? && current_user.administrador) ? Avaliacao.all : Avaliacao.moderadas
    @avaliacoes = @avaliacoes.por_nome_empresa(params[:empresa]) unless (params[:empresa].nil? || params[:empresa] == "")
    @avaliacoes = @avaliacoes.por_nome_usuario(params[:usuario]) unless (params[:usuario].nil? || params[:usuario] == "")
    @avaliacoes = @avaliacoes.por_situacao(params[:status]) unless (params[:status].nil? || params[:status] == "")

    respond_to do |format|
      format.html { render "index"}
    end
  end
end

app/helpers/avaliacoes_helper.rb
module AvaliacoesHelper
end

app/views/avaliacoes/_form.html.erb
<%= form_for(@avaliacao, :html => {:class => 'form-horizontal'}) do |f| %>
    <% if @avaliacao.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@avaliacao.errors.count, "error") %> prohibited this avaliacao from being saved:</h2>

          <ul>
            <% @avaliacao.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">

      <div class="col-lg-1"></div>
      <div class="col-xs-12 col-lg-10">
        <section class="panel">
          <div class="panel-body" style="padding-bottom: 30px;">
            <h2>Contratação</h2>


            <% if @avaliacao.new_record? %>

                <div class="col-lg-12">
                  <label class="col-lg-2 control-label">Nome da Empresa</label>
                  <div class="col-lg-10" sqtyle="margin-top: 13px;">
                    <%= f.text_field :empresa_id, :class => 'form-control',:placeholder => "Digite o nome da empresa", :value => '', :id => 'buscar_empresa'%>
                  </div>
                </div>
                <script type="text/javascript">
                    $(document).ready(function() {
                        var imagem = true;

                        $('#buscar_empresa').tokenInput("<%= autocomplete_empresas_path %>", {
                            zIndex:1000,
                            crossDomain: false,
                            tokenLimit: 1,
                            theme: "facebook",
                            minChars: 3,
                            hintText: "Digite um termo para a pesquisa do destinatário",
                            noResultsText: "Nenhum resultado",
                            searchingText: "Pesquisando...",
                            onAdd: function(item){
                                $(document.getElementsByName('carregando')).remove();
                                imagem = true;
                            },
                            onDelete: function(item){
                                imagem = true;
                            },
                            resultsFormatter: function(item) {
                                var nome = item.name;

                                var imagem = "<img src=" + item.img_src + " onError=\"this.onerror=null;this.src='/assets/user.jpg';\" class=\"img-circle img-token\" style='margin:3px;' width='20px' height='20px'/>"


                                return "<li class=\"token-list\" style='background-color: #FFF;'><div class=\"image pull-left\">" + imagem + "</div><p style='margin-left: 25px;'>" + nome + "</p></li>"
                            },
                            noResult: function(item){
                                $(document.getElementsByName('carregando')).remove();
                                imagem = true;
                            }
                        });

                        $("#token-input-buscar_empresa").keypress(function (){
                            if (($("#token-input-buscar_empresa").val().length >=3) && imagem){
                                $($("#token-input-buscar_empresa").parent().parent()).append('<%= image_tag "loading_blue.gif", :size=>'25x25', :name=>'carregando', :align => 'right'%>');
                                imagem = false;
                            }
                        });

                        $("#token-input-buscar_empresa").keyup(function(e){
                            var keycode =  e.keyCode ? e.keyCode : e.which;
                            if((keycode == 8) && ($("#token-input-buscar_empresa").val().length<3)){
                                $(document.getElementsByName('carregando')).remove();
                                imagem = true;
                            }
                        });
                    });
                </script>
                <br> <br>

            <% else %>
                  <% f.hidden_field :empresa_id, :value => @avaliacao.empresa_id %>
                  <p style="text-align: center"><label class="control-label" style="font-size: 14pt;">Nome da Empresa: <%= @avaliacao.empresa.nome %></label></p>
            <% end %>



            <div class="col-lg-12">
              <div class="col-lg-6" style="margin-left: -5px;">
                <label class="col-lg-4 control-label" style="text-align: center;margin-top: 12px;">Data (mês/ano)</label>
                <div class="col-lg-8" style="margin-top: 12px;">
                  <%= f.text_field :inicio_contrato, :class => 'form-control', :placeholder => 'ex: maio/2015' %>
                </div>
              </div>

              <div class="col-lg-6">
                <label class="col-lg-4 control-label" style="text-align: center;margin-top: 12px;">Final do Estágio</label>
                <div class="col-lg-8" style="margin-top: 12px;">
                  <%= f.text_field :final_contrato, :class => 'form-control', :placeholder => 'ex: outubro/2015' %>
                </div>
              </div>
            </div>

          </div>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-1"></div>

      <div class="col-xs-12 col-lg-10">
        <section class="panel">
          <div class="panel-body" style="padding-bottom: 30px;">
            <h2>Benefícios</h2>

            <div class="col-xs-12 col-lg-4">
              <label class="checkbox-inline">
                <%= f.check_box :vale_transporte %>  Vale Transporte
              </label>
            </div>

            <div class="col-xs-12 col-lg-4">
              <label class="checkbox-inline">
                <%= f.check_box :ticket_refeicao %> Ticket Refeição
              </label>
            </div>

            <div class="col-xs-12 col-lg-4">
              <label class="checkbox-inline">
                <%= f.check_box :ticket_alimentacao %> Ticket Alimentação
              </label>
            </div>

            <div class="col-xs-12 col-lg-4">
              <label class="checkbox-inline">
                <%= f.check_box :plano_saude %> Plano de Saúde
              </label>
            </div>

            <div class="col-xs-12 col-lg-4">
              <label class="checkbox-inline">
                <%= f.check_box :plano_dentario %> Plano Dentário
              </label>
            </div>

            <div class="col-xs-12 col-lg-4">
              <label class="checkbox-inline">
                <%= f.check_box :descontos %> Descontos em Serviços da Empresa
              </label>
            </div>

          </div>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-1"></div>

      <div class="col-xs-12 col-lg-10">
        <section class="panel">
          <div class="panel-body" style="padding-bottom: 30px;">
            <h2>Cargo</h2>

            <div class="col-xs-6 col-lg-6">
              <div class="form-group">
                <label class="col-lg-4 control-label" style="text-align: center;">Título do Cargo</label>
                <div class="col-lg-8">
                  <%= f.text_field :titulo_cargo, :class => 'form-control', :placeholder => 'ex: estagiário em desenvolvimento' %>
                </div>
              </div>

              <div class="form-group">
                <label class="col-lg-4 control-label" style="text-align: center;">Área de Atuação</label>
                <div class="col-lg-8">
                  <%= f.text_field :area_atuacao, :class => 'form-control', :placeholder => 'ex: manutenção do sistema' %>
                </div>
              </div>

            </div>

            <div class="form-group col-xs-12 col-lg-6">
              <div class="form-group">
                <label class="col-lg-4 control-label" style="text-align: center; margin-top: -13px;">Carga Horária<br>(semanal)</label>
                <div class="col-lg-8">
                  <div class="input-group">
                    <%= f.text_field :carga_horaria, :class => 'form-control', :placeholder => 'ex: 30', :onkeypress => 'return event.charCode >= 48 && event.charCode <= 57' %>
                    <span class="input-group-addon" id="basic-addon2">horas/semana</span>
                  </div>
                </div>
              </div>

              <% #TODO preparar máscara do salário %>

              <div class="form-group">
                <label class="col-lg-4 control-label" style="text-align: center;">Salário (bolsa)</label>
                <div class="col-lg-8">
                  <div class="input-group">
                    <span class="input-group-addon" id="basic-addon2">R$</span>
                    <%= f.text_field :salario, :class => 'form-control', :placeholder => 'ex: 800', :onkeypress => 'return event.charCode >= 48 && event.charCode <= 57'  %>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-1"></div>

      <div class="col-xs-12 col-lg-10">
        <section class="panel">
          <div class="panel-body" style="padding-bottom: 30px;">
            <h2>Atividades</h2>

            <div class="col-xs-12 col-lg-12">
              <h3>Quais foram as suas principais atividades no estágio?</h3>


              <div class="col-xs-12 col-lg-12">
                <%= f.text_area :atividades, :rows => 8, :style => 'width: 100%; padding: 10px'  %>
              </div>

            </div>

            <hr>

            <div class="col-xs-12 col-lg-12">
              <h3>Você possuia algum orientador na empresa, que ajudava com suas dúvidas e dificuldades?</h3>

              <div class="col-xs-12 col-lg-6">
                <div class="col-xs-12 col-lg-12">
                  <%= f.radio_button :orientador, 0 %> Meu orientador <b>ajudava frequentemente</b>.
                </div>

                <div class="col-xs-12 col-lg-12">
                  <%= f.radio_button :orientador, 1 %> Meu orientador <b> auxiliava ocasionalmente</b>.
                </div>
              </div>

              <div class="col-xs-12 col-lg-6">

                <div class="col-xs-12 col-lg-12">
                  <%= f.radio_button :orientador, 2 %> Eu <b>não possuia</b> um orientador.
                </div>

              </div>

            </div>

          </div>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-1"></div>

      <div class="col-xs-12 col-lg-10">
        <section class="panel">
          <div class="panel-body" style="padding-bottom: 30px;">
            <h2>Avaliação</h2>

            <br>


            <div class="col-xs-12 col-lg-12">
              <h3>Como você define as suas possibilidades de efetivação?</h3>

              <div class="col-xs-4 col-lg-4">
                <%= f.radio_button :efetivacao, 0 %> Provavelmente <b>serei</b> efetivado.
              </div>

              <div class="col-xs-4 col-lg-4">
                <%= f.radio_button :efetivacao, 1 %> Provavelmente <b>não serei</b> efetivado.
              </div>

              <div class="col-xs-2 col-lg-2">
                <%= f.radio_button :efetivacao, 2 %> Fui <b>efetivado</b>.
              </div>

              <div class="col-xs-2 col-lg-2">
                <%= f.radio_button :efetivacao, 3 %> Fui <b>dispensado</b>.
              </div>

            </div>

            <br><hr>

            <div class="col-xs-12 col-lg-12">
              <h3>Quão válido foi o aprendizado durante o seu tempo de estágio?</h3>

              <div class="col-xs-4 col-lg-4">
                <%= f.radio_button :aprendizado, 0 %> Aprendi <b>muito</b> no estágio.
              </div>

              <div class="col-xs-4 col-lg-4">
                <%= f.radio_button :aprendizado, 1 %> Aprendi <b>algumas coisas</b> no estágio.
              </div>

              <div class="col-xs-2 col-lg-4">
                <%= f.radio_button :aprendizado, 2 %> <b>Não aprendi muito</b> no estágio.
              </div>

            </div>

            <br><hr>

            <div class="col-xs-12 col-lg-12">
              <h3>Você indicaria a mesma oportunidade de estágio para algum amigo seu?</h3>


              <div class="col-xs-4 col-lg-4">
                <%= f.radio_button :indicaria, true %> <b>Indicaria</b>.
              </div>

              <div class="col-xs-4 col-lg-4" >
                <%= f.radio_button :indicaria, false %> <b>Não indicaria</b>.
              </div>

            </div>

            <br><hr>

            <div class="col-xs-12 col-lg-12">
              <h3>Deseja fazer mais comentários sobre a sua experiência de estágio?</h3>


              <div class="col-xs-12 col-lg-12">
                <%= f.text_area :comentarios_avaliador, :rows => 10, :style => 'width: 100%; padding: 10px'  %>
              </div>

            </div>



          </div>
        </section>
      </div>
    </div>

    <% #TODO centralizar botões %>

    <div class="actions">
      <div class="btn-group" style="left:50%;margin-left: -129px;">
        <%= f.submit "Salvar Avaliação", :class => 'btn btn-success'%>
        <input class="btn btn-warning" type="reset" value="Limpar Formulário"></button>
      </div>
    </div>

<% end %>

app/views/avaliacoes/edit.html.erb
<% content_for :content do %>

    <h1><i class="fa fa-star-o fa-lg"></i> Nova Avaliação</h1>

    <ol class="breadcrumb" style="margin-top: 30px; margin-bottom: 0px !important;">
      <li><i class="fa fa-home"></i><a href="<%= root_path %>">Início</a></li>
      <li><i class="fa fa-building"></i><a href="<%= avaliacoes_path %>">Avaliações</a></li>
      <li><i class="fa fa-edit"></i>Editar Avaliação</li>
    </ol>

    <br>



    <%= render 'form' %>

<% end %>

app/views/avaliacoes/index.html.erb
<% content_for :content do %>

    <h1><i class="fa fa-star fa-lg"></i> Avaliações</h1>


    <ol class="breadcrumb" style="margin-top: 30px;">
      <li><i class="fa fa-home"></i><a href="<% root_path %>">Início</a></li>
      <li><i class="fa fa-star"></i>Avaliações</li>
    </ol>

    <div class="row">
      <div class="col-xs-12 col-lg-12">
        <section class="panel">
          <div class="panel-body">
            <%= form_tag pesquisar_avaliacoes_path, :method => :get, :class => 'form-horizontal', :role => 'form' do |f|%>
                <div class="form-group">
                  <label class="col-lg-1 control-label">Empresa:</label>
                  <div class="col-lg-10">
                    <%= text_field_tag :empresa, params[:empresa], {:class => 'form-control',:placeholder => "Digite o nome da empresa"}%>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-lg-1 control-label">Aluno: </label>
                  <div class="col-lg-10">
                    <%= text_field_tag :usuario, params[:usuario], {:class => 'form-control',:placeholder => "Digite o nome do aluno"}%>
                  </div>
                </div>
                <% if (logged_in? && current_user.administrador) %>
                    <div class="form-group">
                      <label class="col-lg-1 control-label">Status:</label>
                      <div class="col-lg-10">
                        <%= select_tag "status", options_from_collection_for_select(SituacaoAvaliacao.all, "id", "descricao"), include_blank: "Todos", class: 'form-control'%>
                      </div>
                    </div>
                <%end%>
                <div class="form-group">
                  <div style="text-align: center">
                    <%= submit_tag "Buscar", :class => 'btn btn-primary btn-sm'%>
                  </div>
                </div>
            <%end%>
          </div>
        </section>
      </div>

      <div class="col-lg-12">
        <section class="panel">

          <table class="table table-striped table-advance table-hover">
            <tbody>
            <tr>
              <th style="width: 35px;"><i class="fa fa-user"></i></th>
              <th> Avaliador</th>
              <th style="width: 35px"><i class="fa fa-building"></i></th>
              <th> Empresa</th>
              <% if (logged_in? && current_user.administrador) %>
                  <th><i class="fa fa-flag"></i> Status</th>
              <% end %>
              <th><i class="fa fa-cogs"></i> Ações</th>
            </tr>
            <% @avaliacoes.each do |avaliacao| %>
                <tr>
                  <td style="padding: 0px;"><img width="100%" style="padding-left: 6px;" src="<% root_path %>/images/noavatar.gif" class="img-circle img-responsive"> </td>
                  <td><%= link_to avaliacao.usuario.nome, usuario_path(avaliacao.usuario_id) %></td>
                  <td  style="padding: 0px;"><img width="100%" style="padding-left: 6px;" src="<% root_path %>/images/noavatar.gif"  class="img-circle img-responsive"> </td>
                  <td><%= avaliacao.empresa.nome%></td>
                  <% if (logged_in? && current_user.administrador) %>
                      <td><%= avaliacao.situacao_avaliacao.descricao%></td>
                  <% end %>
                  <td>
                    <div class="btn-group">
                      <%= link_to "", avaliacao_path(avaliacao.id), :class => "btn btn-primary fa fa-plus-square-o", :title => "Detalhar"%>
                      <% if can? :manage, Empresa %>
                        <% if !avaliacao.moderada? %>
                            <%= link_to "", edit_avaliacao_path(avaliacao.id), :class => "btn btn-success fa fa-pencil-square-o", :title => "Editar"%>
                        <%end%>
                        <%= link_to "", avaliacao_path(avaliacao), :method => :delete, :class => "btn btn-danger fa fa-trash-o", :data => {:confirm => ("Tem certeza que deseja excluir essa avaliação?")}, :title => "Excluir"%>
                      <% end %>
                    </div>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </section>
      </div>
    </div>

    <% if logged_in? %>
        <a class="btn btn-success" href="<%= new_avaliacao_path %>"><i class="fa fa-plus"></i> Nova Avaliação</a>
    <% end %>

<% end %>

app/views/avaliacoes/new.html.erb
<% content_for :content do %>

    <h1><i class="fa fa-star-o fa-lg"></i> Nova Avaliação</h1>

        <ol class="breadcrumb" style="margin-top: 30px; margin-bottom: 0px !important;">
          <li><i class="fa fa-home"></i><a href="<%= root_path %>">Início</a></li>
          <li><i class="fa fa-building"></i><a href="<%= avaliacoes_path %>">Avaliações</a></li>
          <li><i class="fa fa-plus"></i>Nova Avaliação</li>
        </ol>

    <br>



      <%= render 'form' %>

<% end %>