config/routes.rb
EstagiandoUFF::Application.routes.draw do

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'

  get 'autocomplete_empresas' => 'avaliacoes#autocomplete_empresas'

  root :to => "usuarios#home"

  resources :usuarios do
    collection do
      get 'cadastro_efetuado'
    end
    member do
      get :confirm_email
      post :admin
    end
  end

  resources :comentarios

  resources :avaliacoes  do
    collection do
      get 'pesquisar'
    end
    member do
      post :aceitar
      post :rejeitar
    end
  end

  resources :SituacaoAvaliacoesController

  resources :empresas

end

app/views/layouts/_header.html.erb
<header class="header dark-bg">
  <div class="toggle-nav">
    <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"></div>
  </div>

  <!--logo start-->
  <a href="<%= root_path %>" class="logo"><img src="<%= root_path %>images/logo.png" style="margin-top:-12px;"></a>
  <!--logo end-->


  <div class="top-nav notification-row">
    <!-- notificatoin dropdown start-->
    <ul class="nav pull-right top-menu">
      <% if logged_in? %>
          <!-- user login dropdown start-->
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <%= image_tag("user.jpg", width: "30", height: "30", :class => 'img-circle img-responsive') %>
                            </span>
              <span class="username"><%= current_user.nome%></span>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
              <div class="log-arrow-up"></div>
              <li class="eborder-top">
                <a href="<%= usuario_path(current_user)%>"><i class="fa fa-user"></i> Perfil</a>
              </li>
              <li>
                <%= link_to " Sair", sign_out_path, method: "delete", :class=>"fa fa-sign-out" %>
              </li>
            </ul>
          </li>
      <% else %>
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <%= image_tag("user.jpg", width: "30", height: "30", :class => 'img-circle img-responsive') %>
                            </span>
              <span class="username"></span>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
              <div class="log-arrow-up"></div>
              <li class="eborder-top">
                <%= link_to " Criar Conta", new_usuario_path, :class=>"fa fa-sign-in" %>
              </li>
              <li>
                <%= link_to " Logar", sign_in_path, :class=>"fa fa-sign-in" %>
              </li>
            </ul>
          </li>
      <% end %>
      <!-- user login dropdown end -->
    </ul>
    <!-- notificatoin dropdown end-->
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu">
      <li class="active">
        <a class="" href="<%= root_path%>">
          <i class="fa fa-home fa-lg"></i>
          <span>Home</span>
        </a>
      </li>
      <li class="active">
        <a class="" href="<%= empresas_path %>">
          <i class="fa fa-building-o fa-lg"></i>
          <span>Empresas</span>
        </a>
      </li>
      <li class="active">
        <a class="" href="<%= avaliacoes_path%>">
          <i class="fa fa-star fa-lg"></i>
          <span>Avaliações</span>
        </a>
      </li>
      <% if logged_in? && current_user.administrador %>
          <li class="active">
            <a class="" href="<%= usuarios_path%>">
              <i class="fa fa-user fa-lg"></i>
              <span>Usuários</span>
            </a>
          </li>
      <%end%>
    </ul>
    <!-- sidebar menu end-->
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="images/favicon.png">

  <title>EstagiandoUFF</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application","font-awesome.min","jquery.easy-pie-chart","bootstrap-fullcalendar","bootstrap","bootstrap-theme","elegant-icons-style","font-awesome","owl.carousel","jquery-jvectormap-1.2.2","fullcalendar","widgets","style","style-responsive","xcharts","jquery-ui-1.10.4","jquery.ketchup" %>
  <%= javascript_include_tag "application","html5shiv","lte-ie7"%>

</head>

<body>

<!-- container section start -->
<section id="container" class="">

<!--header start-->
<%= render 'layouts/header'%>
<!--header end-->

<!--sidebar start-->
<%= render 'layouts/sidebar'%>
<!--sidebar end-->

<!--main content start-->

      <div id="content" class="content">
        <section id="main-content">

          <section class="wrapper">
            <% unless notice.nil? %>
                <div class="alert alert-success fade in m-b-15">
                  <span class="close" data-dismiss="alert">×</span>
                  <i class="fa fa-check fa-2x pull-left"></i>
                  <p><%= notice %></p>
                </div>
            <% end %>
            <% unless flash[:error].nil? %>
                <div class="alert alert-danger fade in m-b-15">
                  <span class="close" data-dismiss="alert">×</span>
                  <i class="fa fa-times fa-2x pull-left"></i>
                  <p><%= flash[:error] %></p>
                </div>
            <% end %>

            <%= yield :content%>
          </section>
        </section>
      </div>
<!--main content end-->
</section>
<!-- container section start -->

<%= javascript_include_tag "Chart","jquery.knob","jquery.slimscroll.min","sparklines","gdp-data","jquery.placeholder.min","jquery.autosize.min","xcharts.min","jquery-jvectormap-world-mill-en","jquery-jvectormap-1.2.2.min","sparkline-chart","scripts","jquery.customSelect.min","jquery.rateit.min","fullcalendar.min","owl.carousel","jquery.sparkline","jquery.nicescroll","jquery.scrollTo.min","bootstrap.min","jquery-ui-1.9.2.custom.min","jquery-ui-1.10.4.min","jquery.ketchup.all.min" %>


<script>

    //knob
    $(function() {
        $(".knob").knob({
            'draw' : function () {
                $(this.i).val(this.cv + '%')
            }
        })
    });

    //carousel
    $(document).ready(function() {
        $("#owl-slider").owlCarousel({
            navigation : true,
            slideSpeed : 300,
            paginationSpeed : 400,
            singleItem : true
        });
    });

    //custom select box

    $(function(){
        $('select.styled').customSelect();
    });

    /* ---------- Map ---------- */
    $(function(){
        $('#map').vectorMap({
            map: 'world_mill_en',
            series: {
                regions: [{
                    values: gdpData,
                    scale: ['#000', '#000'],
                    normalizeFunction: 'polynomial'
                }]
            },
            backgroundColor: '#eef3f7',
            onLabelShow: function(e, el, code){
                el.html(el.html()+' (GDP - '+gdpData[code]+')');
            }
        });
    });



</script>

</body>
</html>